// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import ModelSelectorController from "./model_selector_controller"
application.register("model-selector", ModelSelectorController)
import { DmTest, TurboModalController, LimitVisibleController } from "dm_unibo_common"
application.register("turbo-modal", TurboModalController)
application.register("limit-visible", LimitVisibleController)

