# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0520279027db23a2346510be042d29eaa36fa2190b6b90537636595090830f0725f2adf90fe5709313ff7ea906aa0fab275e024ea19ab0b36ed56bff1e773eb9

test:
  secret_key_base: 0f1b1095160f6077d2736d114bc0f6e8853d1a27faa73531aafdf0a09a8242bbf65c3fdff488fd1eba9dcb94bfc04f83f027a1c9f530d6746b21619d1f67f649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
